Repository AlinTudi98/webCrawler, pull requests merged in 2020-12, with the labels that each got.

#43 Implementare metoda log()
  src/Logger.java
Labels: enhancement

#52 Implementare metoda getSiteMap()
  src/Sitemap.java
Labels: enhancement

#55 Implementare getInstance si sincronizare
  src/Logger.java
Labels: bug

#59 Implementare functie URLParser:parse() pentru fisiere
  src/URLParser.java
Labels: enhancement

#61 Implementare functie URLParser:parse() pentru parametru de tip String
  src/URLParser.java
Labels: enhancement

#62 Documentare clasa Sitemap
  src/Sitemap.java
Labels: documentation

#64 Documentatie URLParser
  src/URLParser.java
Labels: documentation

#70 Implementare metoda search() in clasa Filter
  src/Filter.java
  src/Sitemap.java
Labels: enhancement

#77 Documentare clasa Filter
  src/Filter.java
Labels: documentation

#80 PageCrawler si completare documentatii
  src/PageCrawler.java
  src/Robot.java
  src/StackManager.java
  src/URLString.java
Labels: documentation, enhancement

#84 BUGFIX Config & WordIndexer
  src/Config.java
  src/WordIndexer.java
Labels: bug

#86 Creare schelet main
  src/Main.java
  src/webCrawler.java
Labels: enhancement

#91 BUGFIX URLParser:parse()
  src/Main.java
  src/URLParser.java
Labels: bug

#92 Implementare Main:readArgs()
  src/Config.java
  src/Main.java
Labels: enhancement

#104 Implementare functie Main:processCommand()
  config.txt
  src/Main.java
  src/Robot.java
  src/Sitemap.java
  src/StackManager.java
  src/URLParser.java
Labels: enhancement

#106 Implementare functie main()
  src/Main.java
Labels: enhancement

#110 Bug in functia PushURL
  src/StackManager.java
Labels: bug

#116 Bug fix Sitemap
  src/Sitemap.java
Labels: bug

#118 Eroarea din metoda PageCrawler:parse()
  src/PageCrawler.java
  src/StackManager.java
Labels: bug

#120 Rezolvare diverse buguri
  src/Logger.java
  src/Main.java
  src/PageCrawler.java
  src/StackManager.java
Labels: bug

#122 Rezolvare diverse buguri
  config.txt
  input.txt
  src/Main.java
  src/Sitemap.java
  src/WordIndexer.java
Labels: bug

#123 Bugfix parametri in Main
  src/Main.java
Labels: bug

#126 Rezolvare bug config
  src/Main.java
Labels: bug
